### ISSUE TITLE
Slicer crashes if we attempt to record OpenVR while VolumeRendering is enabled

### ISSUE THREAD

**Issue by markasselin** [KitwareMedical/SlicerVirtualReality#11]
We tried recording some OpenVR footage that included a volume rendering using [OpenBroadcaster](https://obsproject.com/) and its [OpenVR plugin](https://obsproject.com/forum/resources/openvr-input-plugin.534/). Recording behaved as expected when showing models, slices, etc. If we included a volume rendering in the scene, starting recording caused Slicer to immediately crash.

**Comment by jcfr** [comment]
@martinken  : Do you have any experience with OpenBroadcaster ?

**Comment by martinken** [comment]
No experience with OpenBroadcaster, I do know the volume rendering mapper does not work with multisampling. But usually the result is no image as opposed to a crash.

**Comment by jcfr** [comment]
@jbvimort should be able to have a look.

**Comment by lassoan** [comment]
We've figured this out: OBS Studio only crashes if NVidia hardware-based compression is used. If CPU-based video compression option is chosen then recording works well.
