### ISSUE TITLE
vtk_openvr_actions.json not found when opening a scene file from windows explorer.

### ISSUE THREAD

**Issue by lucsdjango** [KitwareMedical/SlicerVirtualReality#112]
vtk_openvr_actions.json is not found, and controller input thus not working, when opening a scene file from windows explorer.

Workaround:
- Open the scene file.
- Close and reopen Slicer3D.
- Open scene file from "recent" menu.

**Comment by cpinter** [comment]
I find the discovery mechanism of these json files inconvenient and restrictive. It would be great changing it, maybe using them as regular resource files and distributing them with the extension.
