### ISSUE TITLE
SlicerVirtualReality extension has build errors with latest Slicer-5.3 version

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/SlicerVirtualReality#118]
Since the last VTK update SlicerVirtualReality fails to build:

https://slicer.cdash.org/viewBuildError.php?buildid=3085845

> D:\D\P\S-0-E-b\SlicerVirtualReality\VirtualReality\MRML\vtkVirtualRealityViewInteractor.h(49,16): error C3668: 'vtkVirtualRealityViewInteractor::HandleGripEvents': method with override specifier 'override' did not override any base class methods [D:\D\P\S-0-E-b\SlicerVirtualReality-build\inner-build\VirtualReality\MRML\vtkSlicerVirtualRealityModuleMRML.vcxproj] [D:\D\P\S-0-E-b\SlicerVirtualReality-build\inner.vcxproj]

**Comment by jcfr** [comment]
Regression has been identified.

It turns that the version of [MR-9892](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9892) that was originally backported into `Slicer/VTK` was updated to use more explicit function names. For example `HandleComplexGestureEvents` instead of `HandleGripEvents`.
