### ISSUE TITLE
Moving of objects should be done using transforms

### ISSUE THREAD

**Issue by markasselin** [KitwareMedical/SlicerVirtualReality#12]
This will allow changes made in the VR viewer (i.e manipulating an object, etc) to be reflected across other views in Slicer.

**Comment by jcfr** [comment]
Agreed.

We gave been discussing this. 

First, the goal is to support the following:
* add objects under a transform
* enable 3D transform visibility

We first need to update some more VTK widgets to work in VR by supporting `double` based events.


Second, we would like to:
* better integrate controller interaction to automatically add a transform
* support scaling, translation, rotation directly using the controller without having to grab the "handle"

Cc: @jbvimort

**Comment by adamrankin** [comment]
See also #27

**Comment by cpinter** [comment]
Moving objects using transforms has been implemented in https://github.com/KitwareMedical/SlicerVirtualReality/commit/503ef1d300f179acbc5069b53482790a0d01db33
