### ISSUE TITLE
No SlicerVirtualReality extension built for Slicer 5.6.0 (Windows)

### ISSUE THREAD

**Issue by che85** [KitwareMedical/SlicerVirtualReality#126]
Hi, @sulentica just installed Slicer 5.6.0 for Windows. There is no SlicerVirtualReality extension available on the ExtensionManarger. (https://slicer.cdash.org/build/3222677) 

In addition, I noticed the extension was built for macOS and Linux, but when opening the module, I am getting a dialog displayed that the extension is not supported on this platform.

Is this a placeholder, or why are there extension(s) built for a platform that is not supported.

![image](https://github.com/KitwareMedical/SlicerVirtualReality/assets/10195822/cad651c7-fb53-4cc2-bcc6-398fd0859c0a)

**Comment by jcfr** [comment]
There is a message indicating it is not supported on macOS and Linux because OpenVR (aka Steam) is not available on these platforms.

This will change after we add support for OpenXR.

Regarding Windows, I will have a look. Thanks again for the report.

**Comment by Jasan-CZ** [comment]
Hi, the same issue. I can't see/find the extension in the ExtensionManager (Slicer 5.6.0). Is there any Slicer vesrison, where the extension is visible and works?

**Comment by jcfr** [comment]
Plan is to fix the extension and alsonhave OpenXR integration by the end of the year. 

@sankhesh and I are actively working on the project and we should expect updates any day.
