### ISSUE TITLE
VR view is totally black after updating to SteamVR 2.1.10

### ISSUE THREAD

**Issue by lucsdjango** [KitwareMedical/SlicerVirtualReality#130]
When enabling the VR view in Slicer 5.4.0, nothing can be seen. The headset and controllers are tracked, but in the headset everthing is black. Worked before SteamVR was updated to version 2.1.10.

Could this be fixed by changing a setting in SteamVR, or installing an older version perhaps?

Help!

**Comment by lassoan** [comment]
The extension is being reworked now to be compatible with OpenXR (see https://github.com/KitwareMedical/SlicerVirtualReality/issues/126#issuecomment-1850475474). As a side product, support of SteamVR may be upgraded, too. I would recommend to try with the latest Slicer Preview Release in a few weeks. Until then the team probably won't have the bandwidth to investigate this issue.

**Comment by jcfr** [comment]
The latest updates allow to successfully visualize and interact with the scene using the controllers.

We are now working on updating the `SlicerPreview` and `SlicerStable` extension to have a working version.

Once the VirtualReality extension available with `SlicerStable` (`5.6.1`) will be working, it will be in maintenance mode and we will add features only in the extension made available through `SlicerPreview`.

![image](https://github.com/KitwareMedical/SlicerVirtualReality/assets/219043/981f11b7-4ff0-4955-bb97-b7af56294b67)
