### ISSUE TITLE
Document OpenXR capabilities

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerVirtualReality#158]
Update README to describe:
* OpenVR vs OpenXR environmens
  * https://github.com/KitwareMedical/SlicerVirtualReality/issues/152
* The different OpenXR runtimes and explain that only can be active at a time, explain how a specific one can be enabled (either through the runtime specific software or using an external tool like `openxr-explorer`[^2] (or `xrsetenvironment`)
* How to set up remote rendering using HoloLens (what to install, how to configure, how to start)[^1]
* Introduce the concept of actions file and bindings and list the ones currently provided.

### Related
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/121#issuecomment-1715831778

[^1]: _Originally suggested by @lassoan in https://github.com/KitwareMedical/SlicerVirtualReality/issues/151#issuecomment-1874770816_
[^2]: https://github.com/maluoi/openxr-explorer

**Comment by Sunderlandkyl** [comment]
> How to set up remote rendering using HoloLens (what to install, how to configure, how to start)

@jcfr Is there a guide on how to set up the OpenXR remote rending with Slicer?
I can get as far as connecting to the HoloLens from Slicer, however I only see the "Receiving" message.

I'm not sure if there are other steps/prerequisites that I need to follow to get the correct environment on Windows?

**Comment by jcfr** [comment]
> however I only see the "Receiving" message.

This was likely related to the following issue:
* https://github.com/Slicer/Slicer/pull/7571

**Comment by jcfr** [comment]
> if there are other steps/prerequisites that I need to follow to get the correct environment on Windows

While you properly setup the environment, I will still update the README to include details related OpenXR.
