### ISSUE TITLE
Seeing nothing but black 

### ISSUE THREAD

**Issue by lucsdjango** [KitwareMedical/SlicerVirtualReality#166]
My Vive Pro headset is displaying nothing but black in version from Sat Jan 13 2024. 3D Slicer version 5.6.1.
Tested with both OpenVR and OpenXR runtimes, with Steam VR version 2.3.4. 

Has worked in previous versions (last tested with 3D Slicer 5.4).

**Comment by jcfr** [comment]
Thanks for the report.

This may be related to:
* https://github.com/Slicer/Slicer/pull/7571

Could you try renaming the file `bin/d3dcompiler_47.dll` found in the Slicer install directory to `bin/d3dcompiler_47.dll.ignore` ?

Note that if a more recent version if not already installed on your system, Slicer will not started, if this is the case let us know.

**Comment by jcfr** [comment]
@lucsdjango If you still have issues using the latest version, do not hesitate to follow-up here and/or create a new issues.
