### ISSUE TITLE
windows: Fix packaging of OpenVR shared library

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerVirtualReality#2]
The `.lib` is currently installed, it should be the `.dll`.

https://github.com/KitwareMedical/SlicerOpenVR/blob/17c78d31edd43fc686c2f38fed4a0212323c79ec/SuperBuild/External_OpenVR.cmake#L50-L52

The following code should be improved:

https://github.com/KitwareMedical/SlicerOpenVR/blob/17c78d31edd43fc686c2f38fed4a0212323c79ec/CMakeLists.txt#L48-L53

**Comment by pieper** [comment]
I can confirm that if I manually copy openvr_api.dll into the qt-loadable-modules directory the VR extension loads and works as expected with today's nightly.

**Comment by jcfr** [comment]
Thanks for the note. We will fix he install rules.

**Comment by jcfr** [comment]
Closing. Fixed by https://github.com/KitwareMedical/SlicerVirtualReality/pull/23

**Comment by cpinter** [comment]
I did a clean build of SlicerVirtualReality and neither openvr_api.dll nor vtkRenderingOpenVR-9.0.dll were copied to the inner-build/.../qt-loadable-modules/Release, so Slicer could not load the extension.

If this was supposed to be fixed by this ticket then it should be reopened. Thanks!

**Comment by jcfr** [comment]
Thanks for the report. Unless someone address the issue earlier, I will have a look as soon as I am back in the office.

**Comment by jcfr** [comment]
Indeed, for a build tree, you need to pass the `--launcher-additional-settings` flag

Do you have issue with the package installed from the extension manager ?
