### ISSUE TITLE
Expose controller position in the MRML scene

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/SlicerVirtualReality#27]
Add transforms to the MRML scene that contain the current pose of each controller. Maybe also make these transform nodes invoke events as user presses buttons of the controllers.

Mapping controller pose to transform would make many tasks trivial, such as visualizing controllers in the MRML scene, reslicing volumes, clipping models, etc.

**Comment by jcfr** [comment]
@agirault @martinken @LucasGandel Does this approach sound reasonable to you ?

**Comment by lassoan** [comment]
Update transformation matrix in a MRML transform nodes is a pretty lightweight operation, since only those components get notified about changes that added an observer specifically to that.

**Comment by lassoan** [comment]
Controller pose is now available in the scene. Button presses do not generate events (may be implemented in the future).
