### ISSUE TITLE
Oculus Rift controllers do not work

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/SlicerVirtualReality#28]
One user reported that Oculus Rift controllers do not work. Probably it is because Oculus Rift controllers generate different events than HTC Vive and Windows Mixed Reality controllers.

Maybe this will be fixed at some point either in OpenVR (so that Oculus Rift uses that same events as other controllers) or in VTK (by explicitly handling Oculus Rift controller events).

**Comment by jcfr** [comment]
Could you create an issue in [VTK issue tracker](https://gitlab.kitware.com/vtk/vtk/issues) ? 

Cc: @martinken

**Comment by cpinter** [comment]
The problem has been fixed in VTK by this commit
https://gitlab.kitware.com/vtk/vtk/commit/a6fc9e520b6bf2722bf1a113c2aba7189bfac592

**Comment by dzenanz** [comment]
I am using Slicer 4.10.1, and I could not figure out how to "move" the volume rendered image "closer" to me using Oculus controlers. I think I found how to scale the world and maybe rotate it around me. Is this still a problem, or I just did not figure out the controls yet?

**Comment by lassoan** [comment]
You can pull the model towards you (the same way as you translate/rotate). You can also fly closer.

If you make the model scale very large then you may feel that you don't get much closer by pulling it with two controllers. It is because if the object is 100m away and you pull it closer by 50cm then you don't see much size change. You can set the scale 1:1 or smaller using the slider on the GUI.

**Comment by dzenanz** [comment]
> You can pull the model towards you. You can also fly closer.

There seems to be a limit how close I can pull the model towards me. But I can fly closer to it, and even into it, which is a sort of a work-around.

**Comment by lassoan** [comment]
> There seems to be a limit how close I can pull the model towards me

There is no such limit. What makes you feel that there is a limit?

**Comment by adamrankin** [comment]
This sounds like the same behaviour when zooming in the 3D window. There is
a finite distance you can zoom in Slicer.

**Comment by dzenanz** [comment]
I cannot zoom in as close as shown [here](https://youtu.be/F_UBoE4FaoY?t=179). I don't hit the near clipping plane without flying into the volume, and even then the near clipping plane is very close to the eye so it is hard to see anything.

**Comment by lassoan** [comment]
Only the zoom has a fixed range, so probably you think you are grabbing and pulling it closer but you actually zoom in. I would recommend to scale down the object of interest to about a 10x10x10cm cube (by two-handed grab) and pull it to be right in front of you (between your hands), then scale up (by two-handed grab).

**Comment by dzenanz** [comment]
> and pull it to be right in front of you

This is the part I haven't figured out yet. What control does that? I only found "two handed grab" and "flying" (the right joystick). As far as I can tell, the other controls (one-handed grab, A, B, X, Y buttons and left joystick) don't do anything. "Oculus" and "Menu" buttons invoke Oculus-specific menus.

Also, the readme might need an update in section [how-to-set-up-my-oculus-rift-headset](https://github.com/KitwareMedical/SlicerVirtualReality#how-to-set-up-my-oculus-rift-headset).

**Comment by lassoan** [comment]
First scale it down. It makes all distances small, so with two-handed grab you can easily and pull it to right in front of you. For this pulling, keep your hands at a fix distance from each other (to not alter the scaling), reach out, press the buttons, bring the object to you, and release the buttons.

**Comment by lassoan** [comment]
Also note that when you are inside an object then pressing the grab button will grab the object itself. You can disable this by right-click on the object in Data module and uncheck "Toggle selectable".

**Comment by dzenanz** [comment]
> keep your hands at a fix distance from each other (to not alter the scaling)

This was the trick! I guess I subconsciously widened my hands as I moved them closer, thus maxing out the scaling relatively quickly.

Now I feel like I have a good grasp of the controls. Thanks!

**Comment by lassoan** [comment]
Great! Could you try add some notes to the [README.md](https://github.com/KitwareMedical/SlicerVirtualReality/blob/master/README.md) to help others understanding the behavior right away? (anything that would have helped you if it was available)

**Comment by lassoan** [comment]
Should we lock scaling by default?

**Comment by dzenanz** [comment]
PR #67 for readme update.

**Comment by cpinter** [comment]
I think scaling is essential when you do two-handed world manipulation, just because of the issue discussed above. You need to be able to scale your movements. I think what would solve this confusion is a platform under the scene that has a fixed size in the physical coordinate system (so when you scale the world up it seems to be shrinking). That would solve a lot of problems because then you'd see that it is actually much farther away as well than you'd think.
