### ISSUE TITLE
Allow changing size scale using a slider

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/SlicerVirtualReality#31]
Currently, scale is determined from the distance from the camera focal point, but instead the scale should be possible to set directly (by default 1.0x = object appear as in real life).

**Comment by lassoan** [comment]
@jcfr, could you please add salchoueib (Sal Choueib, an intern at the PerkLab) to the project? He would work on this issue.

**Comment by jcfr** [comment]
Of course, could you either ask thet he/she create an account on GitHub or check if there is a typo in the username ? The following page doesn't seem to exist: https://github.com/salchoueib

**Comment by jcfr** [comment]
All set. @salehchoueib was added as a collaborator with Write access.

**Comment by lassoan** [comment]
Great, thank you!

**Comment by lassoan** [comment]
@jcfr I cannot assign this issue to @SalehChoueib. Could you check what could be the problem?

**Comment by jcfr** [comment]
@SalehChoueib first needs to accept the invite:

![image](https://user-images.githubusercontent.com/219043/40076123-137c71a2-584c-11e8-85e9-68cda3bf93b1.png)

**Comment by lassoan** [comment]
Oh, yes, he accepted it and it is all good now! Thanks.

**Comment by cpinter** [comment]
Feature is functional in commit https://github.com/KitwareMedical/SlicerVirtualReality/commit/a8f3d8674da442af6c23713bba0b1ea584480d43

Issue can be closed after bumbing the extension index hash, which can be done once the merge request https://gitlab.kitware.com/vtk/vtk/merge_requests/4726 is integrated, and VTK in Slicer updated to include that commit.
