### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bluels** [KitwareMedical/SlicerVirtualReality#32]
Error:
CMake Error at D:/slicerbuild64d1/VTKv9/CMake/vtkModuleAPI.cmake:120 (message):
Requested modules not available:
 vtkRenderingOpenVR
 Call Stack (most recent call first):
D:/slicerbuild64d1/VTKv9-build/VTKConfig.cmake:76 (vtk_module_config)
VirtualReality/Widgets/CMakeLists.txt:6 (find_package)

do i need to rebuild slicer? how to enable the vr module in slicer (debug 64), new to this, need a detailed guidance. Really thanks！

my environment:
Visual Studio: 2013, Update 5 
Qt: qt-4.8.7-64-vs2013-deb
OS：Win10 64 

thanks!

**Comment by lassoan** [comment]
SlicerVirtualReality requires Qt5 / VTK9 / OpenGL2 rendering backend.

**Comment by bluels** [comment]
thanks!  i use the command below to start slicer.  but when i click the extension button，the slicer crash.
./Slicer.exe  --launcher-additional-settings C:\path\to\SlicerVirtualReality-build\inner-build\AdditionalLauncherSettings.ini --additional-module-paths C:\path\to\SlicerVirtualReality-build\inner-build\

the error is:
 An OpenGL Core Profile was requested, but it is not supported on the current platform. Falling back to a non-Core profile. Note that this might cause rendering issues.
QWindowsWindow::setGeometry: Unable to set geometry 835x570+543+176 on QWidgetWindow/'qSlicerExtensionsManagerDialogWindow'. Resulting geometry:  835x679+543+176 (frame: 9, 38, 9, 9, custom margin: 0, 0, 0, 0, minimum size: 556x679, maximum size: 16777215x16777215).
[26960:3316:0525/121959.844:INFO:CONSOLE(1)] "JQuery not loaded - Failed to trigger webkitvisibilitychange", source:  (1)
Backtrace:
        GetHandleVerifier [0x0000000182673EC5+482501]
        GetHandleVerifier [0x000000018267E258+524376]
        QWebEngineUrlSchemeHandler::_q_destroyedUrlSchemeHandler [0x000000018254C500+3344]
        QWebEngineCookieStorePrivate::q_func [0x000000018369C303+1448019]
        QWebEngineCookieStorePrivate::q_func [0x000000018369C1D6+1447718]

need help. really thanks! how to debuge the slicervirtualreality?

**Comment by lassoan** [comment]
Do you use the SlicerVirtualReality extension with a Slicer that you built?

Did you build Qt or downloaded pre-built Qt? Have you selected to install WebEngine component when you installed Qt?

**Comment by lassoan** [comment]
If you keep having problems with WebEngine then you may disable building extension manager when you configure you Slicer build.

**Comment by cpinter** [comment]
This is probably not related to the error you get but the "--additional-module-paths C:\path\to\SlicerVirtualReality-build\inner-build\" won't be enough to load the module. You'll need "...inner-build\lib\Slicer-4.9\qt-loadable-modules\Release", and you need to make sure that the folder of the openvr_api.dll and vtkRenderingOpenVR-9.0.dll are also included (because they are still not deployed to the right place when you build it yourself - I just copy it to the Release folder I mentioned above)

**Comment by lassoan** [comment]
These are also described in the readme file - https://github.com/KitwareMedical/SlicerVirtualReality#for-developers

**Comment by bluels** [comment]
Really thanks for all your response！
@lassoan 
1.yes, i use the SlicerVirtualReality extension with a Slicer that i built.
2. i use the downloaded pre-build qt (the version: qt-opensource-windows-x86-5.10.1, Path:Qt5.10.1\5.10.1\msvc2015_64\bin, i also change vs2013 to vs2015), and i have selected the WebEngine component when  installed Qt.

the question is solved successfully by change the path “--additional-module-paths C:\path\to\SlicerVirtualReality-build\inner-build\lib\Slicer-4.9\qt-loadable-modules\debug" 

Thanks！@lassoan @cpinter
