### ISSUE TITLE
Expose current pose of VR camera as a linear transform node

### ISSUE THREAD

**Issue by cpinter** [KitwareMedical/SlicerVirtualReality#36]
* Add model of a headset or a person's head wearing a headset
* Whenever the VR camera changes, set parent transform of the avatar model so that it is in the same position
* Need to be able to specify which views show the avatar

**Comment by cpinter** [comment]
Yes it could be a good generic solution and the applications could decide what to do with the transform exactly.

**Comment by adamrankin** [comment]
I second the exposing VR camera transform as a transform node. I will look into it after I finish up this data collection module.
