### ISSUE TITLE
Find_Package(SlicerVirtualReality) failure, missing VTK component

### ISSUE THREAD

**Issue by adamrankin** [KitwareMedical/SlicerVirtualReality#44]
When configuring an extension that depends on SlicerVirtualReality, I get the following message:

Error message:

```cmake
CMake Error at C:/d/Slcr/S4R/VTKv9/CMake/vtkModuleAPI.cmake:140 (message):
  Requested modules not available:

    vtkRenderingOpenVR
Call Stack (most recent call first):
  C:/d/Slcr/S4R/VTKv9-build/VTKConfig.cmake:130 (vtk_module_config)
  C:/d/Slcr/SVRR/inner-build/SlicerVirtualRealityConfig.cmake:13 (find_package)
  C:/d/Slcr/S4/Extensions/CMake/SlicerBlockAdditionalLauncherSettings.cmake:46 (find_package)
  C:/d/Slcr/S4R/Slicer-build/UseSlicer.cmake:279 (include)
  CMakeLists.txt:18 (include)
```

**Comment by cpinter** [comment]
I got this all the time when my build was not a clean build and when I built from the command line not VS. If you open the superbuild solution in VS and build from there it should work.

**Comment by cpinter** [comment]
Right. I only use it from a python-only extension and it's not an issue there, so I don't have any working examples for this.

Maybe we need to specify it somewhere in the SlicerVR CMake?

**Comment by adamrankin** [comment]
Huh, a clean build worked. I wonder if it has to do with adding vtkRenderingOpenVR as an external module.
