### ISSUE TITLE
Add subject hierarchy plugin to disable selectable flag

### ISSUE THREAD

**Issue by cpinter** [KitwareMedical/SlicerVirtualReality#47]
The selectable flag has existed for a long time in Slicer, but VR is currently the only place it is actually used as far as I know. The user might want to disable it, for example if some objects in the scene are interactive and others aren't (see pedicle screw placement when you don't want the vertebrae to be movable by the user only the screws).

I propose adding an SH plugin that would add a menu action for this selectable flag for both nodes and folders.
@jcfr @pieper @lassoan what do you think?

**Comment by pieper** [comment]
yes - that makes sense to me.  That's more-or-less what the original intent of the flag meant, so it would be great to see it used.
