### ISSUE TITLE
Model hierarchy properties are ignored in virtual reality view

### ISSUE THREAD

**Issue by cpinter** [KitwareMedical/SlicerVirtualReality#48]
Model hierarchy properties not applied in VR: when color or opacity is set through a model hierarchy node, the model's individual color and opacity is shown despite they showing up correctly in a regular 3D view

**Comment by lassoan** [comment]
Why is this happening and why don't we want to fix it?

**Comment by cpinter** [comment]
This particular issue with the model hierarchies I don't have capacity to fix among the more important VR issues and all the other projects I'm working on. To me it does not seem important enough to spend hours trying to figure out why this traditionally buggy feature does not work in VR.

However I wanted to record this somewhere.

**Comment by lassoan** [comment]
I agree that it is not a very commonly used feature (only important for viewing large atlases).

VR uses the same displayable managers as non-VR views. It is odd that they behave differently.

**Comment by pieper** [comment]
Agreed that the modelhierarchy visualization features have always been buggy.  Since dissemination of atlases is moving to openanatomy.org we should consider removing any special features for that use case that are hard to maintain.

**Comment by cpinter** [comment]
There is something wrong with how actors are added or set up in the VR renderer. I'll look into the slice view display issue ([#33](https://github.com/KitwareMedical/SlicerVirtualReality/issues/33
)) next week. There is a small chance that the root of that problem is connected to the volume rendering not showing up ([#41](https://github.com/KitwareMedical/SlicerVirtualReality/issues/41)) and with this model hierarchy property issue. In that case I'll fix this one too.

Indeed, the particular feature of this topic is mainly used for atlases, and also the model hierarchy is in general not too reliable (I even made it crash after 5 drag&drops). Maybe we should use a customized subject hierarchy in the Models module where the properties of individual models can be seen in the same way, but instead of having this branch property feature dynamic, It could just apply a certain property on the individual model nodes.

By the way if you don't agree with having this garbage bin like ticket for these issues you're welcome to rename it to the one issue it contains now.

**Comment by cpinter** [comment]
The change https://github.com/Slicer/Slicer/commit/e9f25f8c980e6e9b933518bb472f89858b3f0fe3#diff-24559decf1956a02b77a9321e64cfadd solved this issue. Closing.

**Comment by cpinter** [comment]
Actually I think it was rather this one https://github.com/Slicer/Slicer/commit/2a5d8dc43197e6b9a49184a917d204d03bdd95b7#diff-935cfa1ad640cc957cd6fb1519cc08db.

The point is that this has been fixed by subject hierarchy driving the common model display properties.
