### ISSUE TITLE
Setting vtkOpenVRRenderWindow::TrackHMD to false stops rendering

### ISSUE THREAD

**Issue by adamrankin** [KitwareMedical/SlicerVirtualReality#55]
Based on the name and a quick look at the code, rendering should continue, but the headset should no longer drive the virtual camera.

Will continue to investigate, but would very much appreciate any help/insight.

**Comment by adamrankin** [comment]
Merge request is here:

https://gitlab.kitware.com/vtk/vtk/merge_requests/5268

If it gets accepted, could we cherry pick it into Slicer?

**Comment by adamrankin** [comment]
@jcfr would it be possible to cherry pick
502cf75e60b2b9274f0e8b5a60bc9f8bc81100a1

I didn't properly squash my MR before they merged it, so there's 4 commits involved, but perhaps you can get away with just cherry picking that one?

**Comment by jcfr** [comment]
All set. Thanks for contributing fix to VTK :pray: 

Slicer/VTK fork has been [updated](https://github.com/Slicer/VTK/commits/slicer-v8.2.0-2018-10-02-74d9488523). See also corresponding Slicer change: [r27992](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27992)
