### ISSUE TITLE
Add ability to hide/show tracking references

### ISSUE THREAD

**Issue by adamrankin** [KitwareMedical/SlicerVirtualReality#58]
Collaborating researcher needs to present a clean VR experience for vision research.

Add hide/show functionality for Lighthouse models
<optional> Add UI element to control this functionality

**Comment by adamrankin** [comment]
@lassoan @cpinter @jcfr should I add a UI element to this option?

**Comment by lassoan** [comment]
I guess Adam means that we should hide the models of the HTC lighthouses:

![](https://cdn0.vox-cdn.com/thumbor/qU3FsPI8cVtfEu1nZRElzuN6zuE=/800x0/filters:no_upscale()/cdn0.vox-cdn.com/uploads/chorus_asset/file/6288631/Vive-Lighthouses.0.jpg)

**Comment by jcfr** [comment]
Gotcha. Make sense :+1:

**Comment by adamrankin** [comment]
https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L195

**Comment by adamrankin** [comment]
MRML is done, adding GUI now

**Comment by adamrankin** [comment]
See https://github.com/KitwareMedical/SlicerVirtualReality/pull/59
