### ISSUE TITLE
Python wrapping of vtkOpenVR*/SlicerVirtualReality

### ISSUE THREAD

**Issue by adamrankin** [KitwareMedical/SlicerVirtualReality#61]
This is just a ticket to track any progress towards python wrapping of vtkOpenVR classes. @jcfr you had followed up with this, and there was a solution in VTK and a MR in progress

You had pushed changes to https://github.com/Slicer/VTK/tree/slicer-v8.2.0-2018-10-02-74d9488523

However, I am still unable to access vrView().renderWindow() correctly

**Comment by adamrankin** [comment]
This may be because I am in a developer build. Let me investigate a bit.

**Comment by adamrankin** [comment]
Hmm, have all DLL and pyd files in PATH or PYTHONPATH locations, still not available.

**Comment by lassoan** [comment]
VTK is completely reworking its module system (changes have just been integrated into VTK master). OpenVR is a special case, as it is an external module hosted in the main VTK repository. This use case most likely will not be supported anymore. So I'm not sure if it is worth spending any time with improving the current Python wrapping infrastructure.

Can you survive with workarounds (adding methods to already wrapped Slicer classes, etc.) for a couple of months?

**Comment by jcfr** [comment]
> This use case most likely will not be supported anymore

That said, we plan to integrate support for this in the VTK release anyway. See https://gitlab.kitware.com/vtk/vtk/merge_requests/4986

It is expected to work.

**Comment by adamrankin** [comment]
> Can you survive with workarounds (adding methods to already wrapped Slicer classes, etc.) for a couple of months?

Yup!

**Comment by adamrankin** [comment]
@jcfr Sorry to hassle, but any update available?

**Comment by jcfr** [comment]
@adamrankin At that time resources is quite sparse to address issues like this one, at that stage I only have funding to move forward with the Python3 transition of Slicer. And I am working on having resources to support the c++11 transition.

**Comment by cpinter** [comment]
@adamrankin Can you please give some context about why you closed the ticket? Has this been resolved, if yes, how?

**Comment by adamrankin** [comment]
With #82, and if I understand it correctly, I think we will have to rewrite the CMake to be a separate project that uses VTK (and not an external module). In that case, we will be using the VTK module commands which include python wrapping.

**Comment by cpinter** [comment]
Thanks for the context. So it seems that this issue is neither fixed nor impossible/outdated, so it is still something to happen. Usually I like tickets to be kept open until it is confirmed it is fixed, but since we can assume wrapping will be implicitly added, I'm OK with this having been closed.
