### ISSUE TITLE
Expose OpenVR camera as a vtkMRMLCameraNode

### ISSUE THREAD

**Issue by adamrankin** [KitwareMedical/SlicerVirtualReality#68]
It would be nice if this was implemented, so that we could parent a transform to the OpenVR camera in Slicer.

@jcfr @lassoan any opinion on how much work this would be? I haven't yet started digging

**Comment by lassoan** [comment]
Matching cameras to views is quite a tricky logic, it would be better not to mess with that. Also, camera positioning by transforms relative (does not set absolute position/orientation).

I would recommend to add a manual camera control feature to virtual reality module, which would observe a transform and set absolute camera position from that.

**Comment by adamrankin** [comment]
That's what my initial exploration had told me, I was just hoping you had some magic solution.

I will add that behaviour to the VR module.

**Comment by adamrankin** [comment]
@lassoan Should I still use the MRML node reference subsystem, or bypass it?

**Comment by lassoan** [comment]
If you want to make this a developer-only API (not exposed on the GUI, only accessed via a module, setting not saved in the scene) then you can do it any way you want. There is no need for node references, just make sure you can get access to the VTK API that stops automatic camera updates and you can inject custom camera pose.

If you want to be able to save settings in the scene, implement this feature in SlicerVirtualReality module, or expose it on the GUI, then you need to do it properly (implement scene read/write, use node references, etc.).
