### ISSUE TITLE
SlicerVirtualReality in Unity3D

### ISSUE THREAD

**Issue by lucabror** [KitwareMedical/SlicerVirtualReality#70]
Hi,
Congrats for this 3DSlicer extension. 
Is it possible to visualize this tool inside Unity 3D environment?
This could be very useful for some additional UI functions.
Thank you
Luca

**Comment by lassoan** [comment]
Unity is a completely different framework, you cannot utilize it in Slicer in any way. We are constantly improving SlicerVirtualReality (adding 3D markup manipulation, immersive GUI widgets, laser pointer, etc). Your inputs and contributions are welcome.
