### ISSUE TITLE
VR_Init FailedUnable to init VR runtime: Interface Not Found (105)

### ISSUE THREAD

**Issue by chene77** [KitwareMedical/SlicerVirtualReality#77]
hi,

In the last few nightly (Oct 02/05/07) the SlicerVirtualReality is unable to connect to the steamVR.

When clicking on "connect to hardware", I get "connection failed" in red. The debug/warning message says:
-------------------------
Switch to module:  "VirtualReality"
this->DisplayableManagerGroup 8
VR_Init FailedUnable to init VR runtime: Interface Not Found (105)

Failed to initialize OpenVR RenderWindow
-------------------------

the last line is a warning from QT. 
the second last line is an error message from VTK

The same hardware work just fine in the stale (4.10.2)

**Comment by chene77** [comment]
On the same boot, no reboot. Using HTC VIVE Pro

Sent from Mail for Windows 10

**Comment by adamrankin** [comment]
Do you have a reliable repro setup? If so, when you get back I can
investigate.

**Comment by lassoan** [comment]
This is probably because you updated SteamVR and it is no more compatible with the OpenVR SDK that SlicerVirtualReality extension is built with.

@cpinter mentioned that he had to update OpenVR DLLs on his system manually. Probably he will push a fix soon.

**Comment by cpinter** [comment]
Indeed. Please hang on, I'll update OpenVR asap.

**Comment by cpinter** [comment]
I updated OpenVR and tested it successfully with a recent Slicer (28534). Please try it tomorrow with the nightly preview.

**Comment by cpinter** [comment]
Any news about this? It seems to work now, so I'm going to close the issue unless there are further comments.

**Comment by lassoan** [comment]
Unfortunately, it did not work for SlicerHeart group. Have you tested the factory-built extension?

**Comment by cpinter** [comment]
I only tested it with what I built. Have you?

**Comment by lassoan** [comment]
Hanna at CHOP tested it and wrote this:

I don't think this is working yet.

I downloaded the latest release of Slicer (10/17 version) and updated Steam. I downloaded the Slicer VR module successfully, but after trying to start VR I see a red "X" on the icon.

This is the error message in Slicer:

```
vtkObject (0000017192789190): This OpenGL implementation does not support the required texture size of 262144. Falling back to maximum allowed, 32768.This may cause an incorrect color table mapping.

this->DisplayableManagerGroup 8
VR_Init FailedUnable to init VR runtime: Interface Not Found (105)

Failed to initialize OpenVR RenderWindow
Warning: In d:\d\p\slicer-0-build\vtk\rendering\volumeopengl2\vtkOpenGLVolumeOpacityTable.h, line 191
vtkObject (0000017299AF1770): This OpenGL implementation does not support the required texture size of 262144. Falling back to maximum allowed, 32768.This may cause an incorrect color table mapping.
```

Is there anything else we are supposed to download/update for this?

Thank you.

**Comment by cpinter** [comment]
Not sure what this has to do with VR, it seems like a generic OpenGL error. Of course the fact that VR does not work and this error shows up just when trying to start it means that there is connection. I'll try it on Monday with a nightly install.

What is the data they want to visualize? Anything new or bigger than before, or just the usual?

**Comment by lassoan** [comment]
It is just the usual rendering, which worked before. Quite small volumes. We should test on more computers tomorrow, with the factory-built release.

**Comment by cpinter** [comment]
I tried the latest nightly that has SlicerVR (yesterday the Windows extension builds failed), and it works for me. I used an Acer WMR headset.

I noticed in the past that sometimes if Slicer started SteamVR, then it did not work and needed to restart Slicer (having an up and running SteamVR) to make it connect properly. Maybe they could try that.
