### ISSUE TITLE
vtkMRMLDisplayableManagerFactory.h is not found during Python wrapping

### ISSUE THREAD

**Issue by markasselin** [KitwareMedical/SlicerVirtualReality#8]

**Comment by jcfr** [comment]
@jbvimort Did you experience this problem ?

**Comment by lassoan** [comment]
I haven't noticed this.

@markasselin Was it an error or warning? Build-time or run-time?

**Comment by markasselin** [comment]
This was a build error that we fixed by temporarily disabling python wrapping for that class. I ran a rebuild this morning - the issue is fixed so I will close this ticket.
