### ISSUE TITLE
Add support for OpenXR

### ISSUE THREAD

**Issue by adamrankin** [KitwareMedical/SlicerVirtualReality#80]
Long-term ticket to start the discussion about adding support for OpenXR

Major tasks:

- OpenXR support in VTK
- Create abstract VR API in VTK?
- Transition to abstract API in SlicerVR **OR** Transition to OpenXR API in SlicerVR

Reason:
- Unity drops Open VR support [here](https://blogs.unity3d.com/2020/01/24/unity-xr-platform-updates/)
- Valve eventually moving to OpenXR [here](https://steamcommunity.com/games/250820/announcements/detail/2522527900755718764) and some more info [here](https://store.steampowered.com/news/app/250820/view/2396425843528787269)

Benefits:
- More VR devices supported under a single interface

## Related issues 

* https://github.com/KitwareMedical/SlicerVirtualReality/issues/88
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/91
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/95
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/121
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/122
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/124
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/128

## Related pull requests

**SlicerVirtualReality:**

* https://github.com/KitwareMedical/SlicerVirtualReality/pull/96
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/90
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/85
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/84
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/84
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/90
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/103
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/104
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/105
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/107
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/108
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/109
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/114
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/117
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/119
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/120
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/131
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/135
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/143
* https://github.com/KitwareMedical/SlicerVirtualReality/pull/147

**Slicer:**

* https://github.com/Slicer/Slicer/pull/7516

* https://github.com/Slicer/Slicer/pull/7514

* https://github.com/Slicer/Slicer/pull/7311
  * https://github.com/Slicer/Slicer/pull/7315
  * https://github.com/Slicer/Slicer/pull/7442
  * https://github.com/Slicer/Slicer/pull/7316
  * https://github.com/Slicer/Slicer/pull/7318
  * https://github.com/Slicer/Slicer/pull/7319
  * https://github.com/Slicer/Slicer/pull/7320
  * https://github.com/Slicer/Slicer/pull/7321
  * https://github.com/Slicer/Slicer/pull/7322 
  * https://github.com/Slicer/Slicer/pull/7323 
  * https://github.com/Slicer/Slicer/pull/7324
  * https://github.com/Slicer/Slicer/pull/7325

**CTK:**

* https://github.com/commontk/CTK/pull/1153

**VTK:**

* [MR-10789](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10794) `VR: Resolve "Not rendered" warnings after XR RenderWindow Initialization`
* [MR-10789](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10789) `VR: Add SetInteractionState() API to VR interactor style`
* [MR-10786](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10786) `VR: Update vtkVRRenderWindowInteractor marking ComplexGesture recognition functions as public`
* [MR-10785)](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10785) `VR: Declare AddAction() functions as virtual`
* [MR-10784](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10784) `VR: Update interactor style API adding GetMappedAction()`

* [MR-10783](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10783) `VR: Accommodate separate eye transforms`

* [MR-10778](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10778) `BUG: Recognize OpenVR gesture where buttons are pressed consecutively`

* [MR-10771](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10771) `BUG: Add missing Elevation3DEvent to vtkCommand::EventHasData()`
* [MR-10400](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10400) `ENH: Re-introduce OpenVR API for retrieving last OpenVR pose`
* [MR-9892](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9892) `ENH: Re-introduce support for custom logic handling VR complex gesture`
* [MR-8977](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8977) `vtkInstallCMakePackageHelpers: add find_package hints for OpenVR`

    _Added to that are many other updates adding new capabilities along with the refactoring 
 of `vtkRenderingOpenVR` introducing the `vtkRenderingVR` base module to be used by `vtkRenderingOpenXR` and `vtkRenderingOpenXRRemoting`._

**Comment by cpinter** [comment]
It would be great to support OpenXR indeed. For extra motivation [here](https://www.khronos.org/conformance/adopters/conformant-products/openxr) are the list of devices supporting it (e.g. Oculus Quest, HoloLens).
